# Generated by Django 4.1.7 on 2023-02-20 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobita', '0003_alter_comment_created_at_alter_ip_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 20, 12, 18, 24, 456137)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 20, 12, 18, 24, 456137)),
        ),
        migrations.DeleteModel(
            name='ip',
        ),
    ]
